In [8]:
import torch
import torch.nn as nn

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator

from einops import rearrange, repeat, reduce

from darts.datasets import AirPassengersDataset

In [18]:
abc = torch.randint((3,2,1))
abc

TypeError: randint() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int high, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int high, tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int low, int high, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int low, int high, tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [16]:
abc.T

tensor([[[-0.6682, -0.4577,  1.0239],
         [ 1.6317, -1.6285,  0.9457]]])

In [17]:
repeated = repeat(abc.T, 'a b c -> a b (c d)', d=2)
repeated.T

tensor([[[-0.6682],
         [ 1.6317]],

        [[-0.6682],
         [ 1.6317]],

        [[-0.4577],
         [-1.6285]],

        [[-0.4577],
         [-1.6285]],

        [[ 1.0239],
         [ 0.9457]],

        [[ 1.0239],
         [ 0.9457]]])

In [35]:
dropout = nn.Dropout(p=0.2)
dropout.train(True)
dropout(abc)

tensor([[0.0000, 0.6457, 0.0000, 0.7242, 0.5432, 0.0000, 0.4747, 0.4126, 0.7515,
         0.8499],
        [0.6550, 0.0000, 1.1552, 0.3936, 0.0000, 0.0000, 0.0000, 0.5468, 0.1653,
         1.0448],
        [1.2065, 0.5543, 1.1400, 0.7455, 0.0000, 0.3520, 0.0000, 0.0717, 0.3421,
         0.0000],
        [1.0110, 0.3378, 0.0000, 1.0970, 0.0000, 0.7034, 0.6656, 1.1525, 0.0000,
         0.0000],
        [1.0889, 1.0551, 0.4952, 0.9576, 0.7845, 1.0906, 1.0253, 1.1148, 0.1821,
         0.0000],
        [0.0910, 0.0000, 0.8874, 0.0000, 0.3678, 0.0000, 0.2277, 0.8989, 0.9861,
         0.6103],
        [0.2647, 0.2626, 0.6799, 1.0186, 0.0000, 0.9722, 0.0000, 1.0253, 1.0377,
         0.6132],
        [0.7052, 0.0000, 0.1184, 0.8217, 1.1735, 0.9953, 0.5725, 0.0000, 0.5725,
         0.2633],
        [0.2560, 0.4214, 0.7247, 0.7127, 0.0000, 0.0746, 0.6694, 0.8181, 0.1043,
         0.0000],
        [0.2072, 0.6052, 1.0823, 0.2672, 0.8784, 0.2581, 0.3795, 0.8064, 0.0074,
         0.0904]])

In [36]:
0.1657/(1-0.2)

0.20712499999999998

In [18]:
dropout_rate = 0.5  # 50% dropout rate
dropout = nn.Dropout(p=dropout_rate)

# Example input tensor
x = torch.tensor([1.0, 2.0, 3.0, 4.0])

# Apply dropout during training
dropout.train()  # Set the module in training mode
output = dropout(x)

In [19]:
output

tensor([0., 4., 6., 8.])